# DailyEvent Plugin Configuration

# Localization settings
messages:
  season_change: "§6New season: §e{season}"
  season_current: "§6Current season: §e{season}"

# Season names (customizable)
seasons:
  names:
    BLOOD: "Blood Season"
    FAMINE: "Famine Season"
    STORM: "Storm Season"
    TENEBRE: "Darkness Season"
    ILLUSION: "Illusion Season"
    PARANOIA: "Paranoia Season"
  enabled:
    - BLOOD
    - FAMINE
    - STORM
    - TENEBRE
    - ILLUSION
    - PARANOIA

# Season change time (in-game ticks)
# 0 = 6:00 AM, 6000 = 12:00 PM, 12000 = 6:00 PM, 18000 = 12:00 AM (midnight)
inGameChangeTime: 18000
