name: DailyEvent
main: com.hiskalier.dailyevent.DailyEventPlugin
version: 1.0.0
api-version: 1.20
author: hiskalier
commands:
  season:
    description: Displays or forces the current season
    usage: /season [set <SEASON>]
permissions:
  dailyevent.admin:
    default: op
